### PR TITLE
Fix boot

### LINKED ISSUE #156: Break console doctrine:database:create
Your JMSPaymentCoreBundle::boot method throws an exception when we run the console to create the database !

I think you should find another way (or at least catch the exception) to handle :

```php
if ($this->container->has('doctrine.dbal.default_connection')) {     
    $platform = $this->container->get('doctrine.dbal.default_connection')->getDatabasePlatform();
    $platform->markDoctrineTypeCommented(Type::getType(ExtendedDataType::NAME));
}
```

### PR DESCRIPTION
**Pull request by greg0ire**
This P.R. is supposed to fix #156 . ~~It also contains commits from #163 , so that we can see if it breaks things or not.~~

It contains a B.C - break, because it cannot work for `doctrine/dbal` < `2.3` . Thank @stof for the tips.

### CODE REVIEW

**Comment by greg0ire** [comment]
ping @schmittjoh

**Comment by regularjack** [comment]
Could you remove my commits and rebase with master? #171 (which replaced #163) has been merged to master so those commits are no longer necessary in this PR, tests are now running properly on travis.

About the BC break related to `dbal >= 2.3`, could you explain why this is the case? I took a quick look but couldn't figure out what in this PR requires `dbal >= 2.3`. Thanks.

**Comment by greg0ire** [comment]
OMG it's happening! Looking into this rightaway!

**Comment by greg0ire** [comment]
> About the BC break related to dbal >= 2.3, could you explain why this is the case? I took a quick look but couldn't figure out what in this PR requires dbal >= 2.3. Thanks.

See https://github.com/symfony/symfony/issues/15581#issuecomment-135404592

**Comment by greg0ire** [comment]
Also, this is a BC-break only if you decide bumping version numbers / adding new deps is a BC break. Some people consider it isn't, see [semver itself](http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api). I'm myself not fully decided one way or another on this issue.

**Comment by regularjack** [comment]
Ok, I didn't realise `requiresSQLCommentHint` was introduced in 2.3. 

> Also, this is a BC-break only if you decide bumping version numbers / adding new deps is a BC break. 

Yeah, I was thinking about this and I too am undecided. However, when in doubt I tend to go with what semver says, so I consider this not to be a BC break.

Thanks for fixing this issue. I'll be creating a new release once I fix #167 .

**Comment by greg0ire** [comment]
Thank you for taking the burden of maintaining this project, it's very much appreciated!

**Pull request merged**
