### PR TITLE
Fix method options on ChoosePaymentMethodType form

### PR DESCRIPTION
**Pull request by kengjin**
Fix for setting of method_options
Added ability to pass in options for the payment choice

### CODE REVIEW

**Comment by pro100coder** [comment]
+1

**Comment by regularjack** [comment]
I know it's been a while but would you be available to add tests and documentation? Also, the code is slightly different know because of Symfony 3 support so you would need to rebase and fix the conflicts.

**Comment by regularjack** [comment]
Closing in favour of #188.

**Comment by regularjack** [comment]
Documented [here](http://jmspaymentcorebundle.readthedocs.io/en/latest/payment_form.html#choice-options).

**Pull request closed without merging**
