### PR TITLE
Implement configuration outside the pass

### LINKED ISSUE #173: Unknown column type "extended_payment_data"
This commit https://github.com/schmittjoh/JMSPaymentCoreBundle/commit/8a52a58e7c5e6af6ae6ec02799fdee5a02b0e3c5 introduced this error everytime I launch the console or try to process a payment.

Symfony version: 2.8.9

> Unknown column type "extended_payment_data" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

### PR DESCRIPTION
**Pull request by greg0ire**
Fixes #173 
This configuration does not touch the container, which means there is
nothing to be cached. Once the cache is generated, things don't work
anymore.

### CODE REVIEW

**Comment by greg0ire** [comment]
@hug963 @regularjack , can you confirm this fixes the bug?

**Comment by hug963** [comment]
I tried it quickly and it seems to work.

:thumbsup:

**Comment by regularjack** [comment]
I confirm this works. Thanks @greg0ire and @hug963 for fixing this!

**Comment by greg0ire** [comment]
Thanks for the merge, sorry for the fuck up!

**Comment by regularjack** [comment]
No problem, we're all human. I also should've caught it in the other PR :)

**Pull request merged**
